// Generated by CoffeeScript 1.10.0
(function() {
  Polymer({
    is: "cordova-compass",
    properties: {
      accuracy: {
        notify: true,
        readOnly: true,
        type: Number
      },
      auto: {
        type: Boolean,
        value: false
      },
      heading: {
        notify: true,
        readOnly: true,
        reflectToAttribute: true,
        type: Number
      },
      loop: {
        type: Boolean,
        value: false
      },
      period: {
        type: Number,
        value: 3
      }
    },
    _setHeading: function(heading) {
      return this._setHeading(heading.magneticHeading);
    },
    attached: function() {
      if (this.auto) {
        return this.watch();
      }
    },
    watch: function() {
      return this.$.enabler.promise.then((function(_this) {
        return function() {
          var fn;
          fn = _this.loop ? "watchHeading" : "getCurrentHeading";
          return navigator.compass[fn](_this._setHeading, _this.fire.bind(_this, "cordova-compass-error"), {
            frequency: _this.period
          });
        };
      })(this));
    }
  });

}).call(this);

//# sourceMappingURL=cordova-compass.js.map
